services:
  qdrant:
    image: qdrant/qdrant
    container_name: naturallangdata_qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      QDRANT__LOG_LEVEL: INFO
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: naturallangdata_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  qdrant_data:
